substitutions = [
    'acquired abnormality',
    # 'activity,'
    'age group',
    'amino acid, peptide, or protein',
    'anatomic abnormality',
    'anatomical abnormality',
    'anatomical structure',
    'animal',
    'antibiotic',
    'antibiotic,organic chemical',
    'bacterium',
    # 'behavior',
    'biologic function',
    'biologically active substance',
    'biomedical occupation or discipline',
    'biomedical or dental material',
    'bird',
    'body location or region',
    'body part, organ, or organ component',
    'body space or junction',
    'body substance',
    'body system',
    'cell',
    'cell component',
    'chemical',
    'chemical viewed functionally',
    'chemical viewed structurally',
    # 'classification',
    # 'conceptual entity',
    'clinical attribute',
    'clinical drug',
    # 'conceptual entity,'
    'congenital abnormality',
    'daily or recreational activity',
    'diagnostic procedure,'
    'disease or syndrome',
    'disease/finding]',
    'drug delivery device',
    'educational activity',
    'element, ion, or isotope',
    'embryonic structure',
    'entity',
    'environmental effect of humans',
    'eukaryote',
    'epc]',
    'experimental model of disease',
    'event',
    'family group',
    # 'finding',
    'fish',
    'food',
    # 'functional concept',
    'geographic area',
    'fungus',
    'gene or genome',
    'genetic function',
    # 'governmental or regulatory activity'
    # 'group',
    'group attribute',
    'hazardous or poisonous substance',
    'health care activity',
    # 'health care related organization,'
    'hormone',
    'human',
    # 'human-caused phenomenon or process',
    # 'idea or concept',
    'immunologic factor',
    'indicator, reagent, or diagnostic aid',
    'individual behavior',
    'injury or poisoning',
    'inorganic chemical',
    # 'intellectual product' # this is systematic review/ randomized trial etc!
    'kenalog]',
    'laboratory or test result',
    'laboratory procedure',
    'language',
    'machine activity',
    'mammal',
    'manufactured object',
    'medical device',
    'megace]',
    'mental or behavioral dysfunction',
    # 'mental process,'
    'neoplastic process',
    'moa]'
    'molecular biology research technique',
    'molecular function',
    'natural phenomenon or process',
    'neoplastic process',
    'nucleic acid, nucleoside, or nucleotide,pharmacologic substance',
    'nucleotide sequence',
    # 'occupation or discipline,'
    # 'occupational activity,'
    'organ or tissue function',
    'organic chemical'
    'organism',
    # 'organization'
    'pathologic function',
    'pathological function',
    'patient or disabled group',
    'pe]',
    'pharmacologic substance',
    # 'phenomenon or process'
    'physiologic function',
    'physical object',
    'plant',
    'population group',
    # 'professional or occupational group',
    # 'professional society',
    # 'publication type]'
    # 'qualitative concept'
    # 'quantitative concept'
    'receptor',
    'regulation or law',
    # 'research activity'
    'research device',
    # 'self-help or relief organization',
    'sign or symptom',
    'social behavior',
    # 'spatial concept'
    'substance',
    'temporal concept',
    'therapeutic or preventive procedure',
    'tissue',
    'virus',
    'vitamin',
]
